# Site settings
title: Titel
header-img: img/home-bg.jpg
email: email
copyright_name: Your/Project/Corporate Name
description: "Beschreibung"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://yourdomain.com"
twitter_username: twitter
github_username:  github
facebook_username:  facebook
email_username:  email
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
