# Site settings
title: "Liberale Männer"
header-img: img/home-bg.jpg
email: info@liberale-maenner.org
copyright_name: Oliver Hoffmann
description: "Gleichberechtigung - auch für Männer"
baseurl: "/"
url: "http://www.liberale-maenner.org/"
twitter_username: liberalemaenner
github_username:  ontore
facebook_username:  liberalemaenner
email_username:  info@liberale-maenner.org
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
include: ["_navbar"]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed] 

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      header-img: "img/about-bg.jpg"
      subtitle:  " "
      author: "Liberale Männer"
  -
    scope:
      path: "menu"
    values:
      layout: "page"
      header-img: "img/about-bg.jpg"
      subtitle:  " "
      author: "Liberale Männer"
      navbar: "yes"
