# Site settings
title: "Liberale Männer"
header-img: img/home-bg.jpg
email: info@liberale-maenner.net
copyright_name: Oliver Hoffmann
description: "Gleichberechtigung - auch für Männer"
baseurl: "/"
url: "http://www.liberale-maenner.net/"
twitter_username: liberalemaenner
github_username:  ontore
facebook_username:  liberalemaenner
email_username:  info@liberale-maenner.net
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
include: ["_navbar"]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-cloudinary]

cloudinary:
  cloud_name: liberalemaenner
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"  

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      header-img: "img/about-bg.jpg"
      subtitle:  " "
      author: "Liberale Männer"
  -
    scope:
      path: "menu"
    values:
      layout: "page"
      header-img: "img/about-bg.jpg"
      subtitle:  " "
      author: "Liberale Männer"
      navbar: "yes"
